// SPDX-FileCopyrightText: 2026 The MilkDAWp contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

#include <iostream>

#include "milkdawp/core/ParameterModel.h"

// Regenerates docs/parameters.md's content. See CMakeLists.txt in this
// directory for how to run it.
int main() {
  std::cout << "<!-- Generated by tools/generate-param-docs from core/src/ParameterModel.cpp. "
               "Do not edit by hand. -->\n\n";
  std::cout << "# MilkDAWp 2 parameters\n\n";
  std::cout << "The canonical parameter surface (Phase 1.13), shared by the plugin's APVTS "
               "layout, the app's preferences/MIDI-learn targets, and `MigrateFromV1` (via the "
               "v1 alias column).\n\n";
  std::cout << milkdawp::core::renderParameterDocsMarkdown(milkdawp::core::allParameters());
  return 0;
}
